name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        args: '-latexoption=-file-line-error -latexoption=-interaction=nonstopmode'
        root_file: ""
    - name: Upload result
      uses: actions/upload-artifact@v2-preview
      with:
        name: cours.zip
        path: ./build/*.pdf
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY-MM-DD-HH-mm-ss
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-date
      with:
        format: YYYY-MM-DD
    - name: Create release tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.current-time.outputs.formattedTime }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.current-time.outputs.formattedTime }}
        release_name: Version du ${{ steps.current-date.outputs.formattedTime }}
        draft: false
        prerelease: false
    - name: Release polynomes
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/polynomes.pdf
        asset_name: polynomes.pdf
        asset_content_type: application/pdf
    - name: Release calculdiff
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/calculdiff.pdf
        asset_name: calculdiff.pdf
        asset_content_type: application/pdf
    - name: Release cours
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/cours.pdf
        asset_name: cours-complet.pdf
        asset_content_type: application/pdf
