name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: polynomes.tex
    - name: Upload result
      uses: actions/upload-artifact@v1.0.0
      with:
        name: polynomes.pdf
        path: polynomes.pdf
